---
- name: Install required packages
  apt: name={{item}} state=present
  sudo: True
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - postgresql-contrib

- name: Ensure databases exists
  postgresql_db: name={{item}} encoding='UTF-8' lc_collate='en_US.UTF-8' lc_ctype='en_US.UTF-8' template='template0'
  sudo: True
  sudo_user: postgres
  with_items: postgresql_databases

- name: Ensure DB user has access to the DBs
  postgresql_user: db={{item}} name={{username}} password={{postgresql_password}} priv=ALL state=present role_attr_flags=SUPERUSER
  sudo: True
  sudo_user: postgres
  with_items: postgresql_databases
