---
- hosts: all
  remote_user: "{{username}}"

  roles:
    - apt
    - common
    - locale
    - mosh
    - zsh
    - direnv
    - imagemagick
    - linuxbrew
    - dev
    - npm
    - postgresql
    - rvm
    - first_circle
