---
- name: Install required packages
  apt: name={{item}} state=present
  become: True
  with_items:
    - build-essential
    - curl
    - git
    - m4
    - ruby
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - zlib1g-dev

- name: Install linuxbrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)" creates="{{home_dir}}/.linuxbrew"

- name: Copy zsh hook
  copy: src=zshrc dest={{home_dir}}/.zsh.after/linuxbrew.zsh
